baseURL = "https://mguarascio.com/"
languageCode = "en-us"
title = "Mike Guarascio"
theme = "ink"
googleAnalytics = "G-L2E8FW3B10"

[params]
	subtitle = "Tech, running, parenting, learning"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mguarascio"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/mguarascio"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"